name: 'dune-release'
description: 'Automatically run dune-release in GitHub Actions'
author: 'davesnx'
branding:
  icon: 'package'
  color: 'orange'

inputs:
  packages:
    description: 'Package name(s) for release. Can be a single package or multiple packages as array'
    required: true
  changelog:
    description: 'Path to changelog file'
    required: false
    default: './CHANGES.md'
  github-token:
    description: 'GitHub token for API access'
    required: true
  to-opam-repository:
    description: 'If true, submits a PR to opam-repository'
    required: false
    default: 'true'
  to-github-releases:
    description: 'If true, creates a GitHub release'
    required: false
    default: 'true'
  verbose:
    description: 'If true, shows detailed logging output'
    required: false
    default: 'false'
  include-submodules:
    description: 'If true, includes git submodules in the distribution tarball'
    required: false
    default: 'false'
  opam-repository:
    description: 'Target opam repository in owner/repo format (e.g., ocaml/opam-repository)'
    required: false
    default: 'ocaml/opam-repository'
  build-dir:
    description: 'Build directory for dune-release distribution'
    required: false
  publish-message:
    description: 'Custom message for the GitHub release publication'
    required: false

outputs:
  version:
    description: 'Extracted version from git tag'
  release-status:
    description: 'Status of the release (success/failed)'

runs:
  using: 'node20'
  main: 'dist/index.js'
